name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: psf/black@stable
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
